services:
  taskflow:
    image: ghcr.io/cnafateh/taskflow:latest
    container_name: taskflow
    restart: unless-stopped

    expose:
      - "8080"

    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"

      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=taskflow;Username=taskflow_app;Password=${TASKFLOW_DB_PASSWORD}"

      DataProtection__KeysPath: "/app/keys"

      SeedAdmin__Email: "${SEED_ADMIN_EMAIL}"
      SeedAdmin__Password: "${SEED_ADMIN_PASSWORD}"

    volumes:
      - taskflow_keys:/app/keys

    networks:
      - proxy
      - database

volumes:
  taskflow_keys:

networks:
  proxy:
    external: true

  database:
    external: true