name: CI

on:
  pull_request:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Restore dependencies
        run: dotnet restore ./TaskFlow.Web/TaskFlow.Web.csproj

      - name: Build
        run: dotnet build ./TaskFlow.Web/TaskFlow.Web.csproj -c Release --no-restore